apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: hls-data-pvc
 namespace: rmtp
spec:
 storageClassName: "nfs-medium"
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 950Gi
