apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: rmtp-lb
  name: nginx-rmtp-lb
  namespace: rmtp
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: rmtp-lb
  template:
    metadata:
      labels:
        k8s-app: rmtp-lb
    spec:
      containers:
      - name: nginx-rmtp-lb
        image: nginx
        resources:
          limits:
            cpu: "250m"
          requests:
            cpu: "100m"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          name: lb-config
      volumes:
      - name: lb-config
        configMap:
          name: lb-config
